---
title: "Tarea 2"
author: "Mónica Hernández (B83731)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Cargar librerias
```{r}
library(readxl)
library(dplyr)
library(ggplot2)
```
# Pregunta 1
```{r}
tavid2000_2150 <- read_excel("~/GitHub/Contin/Tarea 2/tavid2000-2150.xls")
tavid2000_2150<-tavid2000_2150%>%mutate(qx=as.numeric(qx))
```

```{r}
tablaHombres <- tavid2000_2150 %>% filter(sex == 1)
tablaMujeres <- tavid2000_2150 %>% filter(sex == 2)
```

### Funciones utiles
```{r}
# kpx <- function(x, k, qx, w) {
#   p<-1
#   qx <- qx %>% mutate(px = 1 - qx)
#   if(k<x){
#     p<-1
#   }else{
#      if (k >= w){
#       p <- 0
#      }else{
#       TABLA <- qx %>% filter((x <= edad) & (edad < k))
#     p <- prod(TABLA$px)
#     }
#   }
#   return(p)
# }

```

```{r}

kpx <- function(x, k, qx, w) {
  if (k == 0) {
    return(1)  # Si k es igual a cero, devuelve 1
  } else {
    if ((x + k) <= w) {
      px <- 1
      for (i in 1:(k + 1)) {
        px <- px * (1 - qx[x + i])  # Calcula el producto de (1 - qx[x + i]) para i en 1 hasta k+1
      }
      return(px)  # Devuelve el resultado del producto
    } else {
      return(0)  # Si (x + k) es mayor que w, devuelve 0
    }
  }
}
```


```{r}
qx_diferida<-function(u,t,qx,x,w){
  return( kpx(x, u , qx, w)-kpx(x, u+t, qx, w))
}

```


# Pregunta 2
```{r}
Ax<-function(x,y,qx,w,i,genero){
  qx<-qx%>% filter(year==y,sex==genero)
  v <- (1 / (1 + i))  
  
  ax <- 0  
  for (k in 0:(w - 1)) {
    ax <- ax + sum(v^(k + 1) * qx_diferida(k,1,qx$qx,x,w))
  }
  return(ax)  

}
```

# Pregunta 3
```{r}
Axn <- function(x, y, qx, w, i,n,genero) {
  
  qx <- qx %>% filter(sex == genero,year == y)
  v <- (1 / (1 + i))
  
  ax <- 0
  if (x + n + 1 <= w) {
    for (k in 0:(n - 1)) {
      ax <- ax + sum(v ^ (k + 1) * qx_diferida(k, 1,qx$qx, x, w))
    }
  } else{
   for (k in 0:(w - 1)) {
      ax <- ax + sum(v ^ (k + 1) * qx_diferida(k, 1,qx$qx, x, w))
    }
  }
  
  return(ax)
}
```

# Pregunta 3
```{r}
SeguroVidaCompleta <- function(qx, w, year,genero) {
  interes <- 0.05
  vidaCompleta <- data.frame()
  for (i in 1:w) {
    seguro <- Ax(i, year, qx, w, interes,genero)
    nueva_fila <- data.frame(i, seguro)
    vidaCompleta <- rbind(vidaCompleta, nueva_fila)
  }
  colnames(vidaCompleta) <- c("edad", paste0("Seguro_",year,"_",genero))
  return(vidaCompleta)
}
```




```{r}
VidaCompleta_mujeres_2024<-SeguroVidaCompleta(tavid2000_2150,115,2024,2)
VidaCompleta_mujeres_2050<-SeguroVidaCompleta(tavid2000_2150,115,2050,2)
```
```{r}
VidaCompleta_hombres_2024<-SeguroVidaCompleta(tavid2000_2150,115,2024,1)
VidaCompleta_hombres_2050<-SeguroVidaCompleta(tavid2000_2150,115,2050,1)
```
## Grafico 
```{r}
vidaCompleta_mujeres<-merge(VidaCompleta_mujeres_2024,VidaCompleta_mujeres_2050,by="edad")
vidaCompleta_hombres<-merge(VidaCompleta_hombres_2024,VidaCompleta_hombres_2050, by="edad")

VidaCompleta<-merge(vidaCompleta_hombres,vidaCompleta_mujeres,by="edad")


ggplot(VidaCompleta, aes(x = edad)) +
  geom_line(aes(y = Seguro_2024_1, color = "Hombres 2024")) +
  geom_line(aes(y = Seguro_2050_1, color = "Hombres 2050")) +
  geom_line(aes(y = Seguro_2024_2, color = "Mujeres 2024")) +
  geom_line(aes(y = Seguro_2050_2, color = "Mujeres 2050")) +
  labs(title = "Comparación del Valor Presente de un Seguro \n para los años 2024 y 2050 ",
       x = "Edad",
       y = "Seguro") +
  scale_color_manual(values = c("Hombres 2024" = "blue", "Hombres 2050" = "darkblue", 
                                 "Mujeres 2024" = "red", "Mujeres 2050" = "darkred")) +
  theme_minimal()
```

 # Pregunta 5
```{r}
SeguroVidaTemporal <- function (qx, w,year, n,genero) {
  interes <- 0.05
  vidaTemporal <- data.frame()
  for (i in 1:w) {
    seguro <- Axn(i, year, qx, w, interes, n,genero)
    nueva_fila <- data.frame(i, seguro)
    vidaTemporal <- rbind(vidaTemporal, nueva_fila)
  }
  colnames(vidaTemporal) <- c("edad", paste0("Seguro_",year,"_",genero))
  return(vidaTemporal)
}
```

```{r}
VidaTemporal_mujeres_2024<-SeguroVidaTemporal(tavid2000_2150,115,2024,10,2)
VidaTemporal_mujeres_2050<-SeguroVidaTemporal(tavid2000_2150,115,2050,10,2)
```
```{r}
VidaTemporal_hombres_2024<-SeguroVidaTemporal(tavid2000_2150,115,2024,10,1)
VidaTemporal_hombres_2050<-SeguroVidaTemporal(tavid2000_2150,115,2050,10,1)
```

```{r}
vidaTemporal_mujeres<-merge(VidaTemporal_mujeres_2024,VidaTemporal_mujeres_2050,by="edad")
vidaTemporal_hombres<-merge(VidaTemporal_hombres_2024,VidaTemporal_hombres_2050, by="edad")

VidaTemporal<-merge(vidaTemporal_hombres,vidaTemporal_mujeres,by="edad")


ggplot(VidaTemporal, aes(x = edad)) +
  geom_line(aes(y = Seguro_2024_1, color = "Hombres 2024")) +
  geom_line(aes(y = Seguro_2050_1, color = "Hombres 2050")) +
  geom_line(aes(y = Seguro_2024_2, color = "Mujeres 2024")) +
  geom_line(aes(y = Seguro_2050_2, color = "Mujeres 2050")) +
  labs(title = "Comparación del Valor Presente de un Seguro Temporal de 10 años\n para los años 2024 y 2050 ",
       x = "Edad",
       y = "Seguro") +
  scale_color_manual(values = c("Hombres 2024" = "blue", "Hombres 2050" = "darkblue", 
                                 "Mujeres 2024" = "red", "Mujeres 2050" = "darkred")) +
  theme_minimal()
```


### Acesso al github
https://github.com/MonicaHB00/Contin.git
