---
title: "Tarea 4- Contingencias de Vida I"
author: "M칩nica Hern치ndez (B83731) y Carlos Andrade ()"
output: html_document
date: "2023-06-14"
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


Pregunta 1
{r}
kpx <- function(x, k, qx, w) {
  if (k == 0) {
    return(1)  # Si k es igual a cero, devuelve 1
  } else {
    if ((x + k) <= w) {
      px <- 1
      for (i in 1:(k + 1)) {
        px <- px * (1 - qx[x + i])  # Calcula el producto de (1 - qx[x + i]) para i en 1 hasta k+1
      }
      return(px)  # Devuelve el resultado del producto
    } else {
      return(0)  # Si (x + k) es mayor que w, devuelve 0
    }
  }
}



Pregunta 2
{r}
Ax <- function(x, i, qx, w) {
  v <- (1 / (1 + i))  # Calcula el valor de v
  ax <- 0  # Inicializa ax en 0
  for (k in 0:(w - 1)) {
    # Calcula la suma de v^(k+1) multiplicado por (kpx(x,k,qx,w) - kpx(x,k+1,qx,w))
    ax <- ax + sum(v^(k + 1) * (kpx(x, k, qx, w) - kpx(x, k + 1, qx, w)))
  }
  return(ax)  # Devuelve el valor de ax
}


Pregunta 3
{r}
axn <- function(x, n, i, qx, w) {
  v <- (1 / (1 + i))  # Calcula el valor de v
  if (x < 0 || i < 0 || x > w) {
    stop("Parametros no son validos")  # Verifica si los par치metros son v치lidos
  }
  axn <- 0  # Inicializa axn en 0
  for (k in 0:(n - 1)) {
    axn <- axn + (v^k * kpx(x, k, qx, w))  # Calcula la suma de v^k multiplicado por kpx(x,k,qx,w)
  }
  return(axn)  # Devuelve el valor de axn
}



Pregunta 4
{r}
sch <- 0 #Seguro Completo Hombres
scm <- 0 #Seguro Completo Mujeres
ath <- 0 #Anualidad temporal Hombres
atm <- 0 #Anualidad temporal Mujeres
  




for (edad in 1:101){
  sch[edad] = Ax(Tablas_de_mortalidad$Edad[edad], 0.08, Tablas_de_mortalidad$`qx Hombres`,110)
  scm[edad] = Ax(Tablas_de_mortalidad$Edad[edad], 0.08, Tablas_de_mortalidad$`qx Mujeres`,110)
  ath[edad] <- axn(Tablas_de_mortalidad$Edad[edad], 5, 0.08, Tablas_de_mortalidad$`qx Hombres`, 110)
  atm[edad] <- axn(Tablas_de_mortalidad$Edad[edad], 5, 0.08, Tablas_de_mortalidad$`qx Mujeres`, 110)
}

tabla_final <- data.frame(
  Edad = 0:100
)
tabla_final$Seguro_Completo_H <- sch
tabla_final$Seguro_Completo_M <- scm
tabla_final$Anualidad_Temp_H <- ath
tabla_final$Anualidad_Temp_M <- atm

