---
title: "Tarea 1"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#FFFFFF"
      fg: "#333333"
      primary: "#2E8B57"
      secondary: "#6A5ACD"
      base_font:
        google: Noto Sans
      heading_font:
        google: Oswald
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

### Carga de paquetes

```{r}

```


### Carga de Archivos 
```{r}
Female.Aggregate <- read.csv("~/GitHub/Contin/Tarea 1/RP-2000 - Female Aggregate - Combined Healthy.csv")
Male_Aggregate <- read.csv("C:/Users/moni1/Dropbox/Mi PC (LAPTOP-2AN4DJNH)/Downloads/Export (2).csv")

```
# Funcion que crea kpx
```{r}
kpx <- function(x, k, qx, w) {
  p<-1
  if ((k > x) & (k < w)) {
    qx <- qx %>% mutate(X1 = 1 - X1)
    TABLA <- qx %>% filter((x <= Row.Column) & (Row.Column < k))
    p <- prod(TABLA$X1)
  }
  return(p)
}
```

# funcion que crea e_x
```{r}
ex <- function(x, qx, w) {
  cantidadAños <- w - x
  suma <- 0
  
  for (i in 1:w - x) {
    prob <- kpx(x, x + i, qx, w)
    suma <- suma + prob
  }
  return(suma)
}
```

#Creacion de las funciones de sibrevivencia 

```{r}
tablaSobrevivencia <- function(x, qx, w) {
  cantidadA <- (w - x)
  tablaSobrevivencia <- data.frame()
  
  for (i in 1:cantidadA) {
    prob <- kpx(x, x + i, qx, w)
    nueva_fila <- data.frame(i, prob)
    tablaSobrevivencia <- rbind(tablaSobrevivencia, nueva_fila)
  }

  return(tablaSobrevivencia)
}

```


# Pruebas
```{r}
tablaVeinte<-tablaSobrevivencia(20,Female.Aggregate,120)
ggplot(data = tablaVeinte, aes(x = prob, y = i)) +
  geom_point(color = "blue", size = 3) +
  labs(
    title = "Grafico de Puntos",  # Título del gráfico
    x = "Eje X",                   # Etiqueta del eje X
    y = "Eje Y"                   # Etiqueta del eje Y
  )
```




